export const CountriesByCode = {
  US: "United States",
  ES: "Spain",
  IT: "Italy",
  DE: "Germany",
  GB: "United Kingdom",
  FR: "France",
  TR: "Turkey",
  IR: "Iran",
  CN: "China",
  RU: "Russia",
  BR: "Brazil",
  BE: "Belgium",
  CA: "Canada",
  NL: "Netherlands",
  CH: "Switzerland",
  PT: "Portugal",
  IN: "India",
  PE: "Peru",
  IE: "Ireland",
  SE: "Sweden",
  AT: "Austria",
  IL: "Israel",
  SA: "Saudi Arabia",
  JP: "Japan",
  CL: "Chile",
  KR: "South Korea",
  EC: "Ecuador",
  PL: "Poland",
  PK: "Pakistan",
  RO: "Romania",
  SG: "Singapore",
  MX: "Mexico",
  AE: "U.A.E.",
  DK: "Denmark",
  NO: "Norway",
  ID: "Indonesia",
  CZ: "Czech Republic",
  RS: "Serbia",
  BY: "Belarus",
  AU: "Australia",
  PH: "Philippines",
  QA: "Qatar",
  UA: "Ukraine",
  MY: "Malaysia",
  DO: "Dominican Republic",
  PA: "Panama",
  FI: "Finland",
  CO: "Colombia",
  LU: "Luxembourg",
  EG: "Egypt",
  ZA: "South Africa",
};
